name: smartfeed
description: "Automation of feeding for bird pet"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  flutter_secure_dotenv: ^1.0.1
  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3
  animated_notch_bottom_bar: ^1.0.3
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2
  firebase_messaging: ^15.2.5
  flutter_secure_storage: ^9.2.4
  package_info_plus: ^8.3.0
  flutter_svg: ^2.1.0

dependency_overrides:
  collection: 1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_secure_dotenv_generator: ^1.0.5
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_no-bg_high.png"
  min_sdk_android: 23

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/illustration/